name:  Create an promtotwiolio_app artifact
on: push
#  push:
#    tags:
#      - 'v*' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - name: build Package
      run: |
        go mod download
        CGO_ENABLED=0 go build -installsuffix 'static' -o promtotwilio_app .
    - name: Debug
      run: ls -ltr
    - name: Create Package zip
      if: github.event_name != 'pull_request'
      run: zip promtotwilio_app.zip promtotwilio_app
    - name: Debug
      run: ls -ltr
